# 텐서 생성 및 변환

In [1]:
import torch
print(torch.tensor([[1,2],[3,4]]))
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [2]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy())

[[1 2]
 [3 4]]


# 텐서의 인덱스 조작

In [3]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0], temp[1], temp[-1])
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
tensor([3., 4., 5.]) tensor([5., 6.])


# 텐서 연산 및 차원 조작

In [4]:
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])
print(w-v)

tensor([2, 2, 3])


In [5]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.shape)
print('-'*30)
print(temp.view(4,1))
print('-'*30)
print(temp.view(-1))
print('-'*30)
print(temp.view(1, -1))
print('-'*30)
print(temp.view(-1, 1))

torch.Size([2, 2])
------------------------------
tensor([[1],
        [2],
        [3],
        [4]])
------------------------------
tensor([1, 2, 3, 4])
------------------------------
tensor([[1, 2, 3, 4]])
------------------------------
tensor([[1],
        [2],
        [3],
        [4]])
